# Generated by Django 4.0.3 on 2022-03-10 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogComments', '0002_remove_blogcomment_replied_to_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCommentReply',
        ),
    ]
