# Generated by Django 4.0.3 on 2022-03-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_numer',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
