# Generated by Django 4.0.3 on 2022-03-11 04:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0003_remove_restaurant_menu_restaurant_logo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResturantFollower',
            new_name='RestaurantFollower',
        ),
    ]
