# Generated by Django 4.0.3 on 2022-03-12 22:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0004_rename_resturantfollower_restaurantfollower'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestraurantLike',
            new_name='RestaurantLike',
        ),
    ]
