# Generated by Django 4.0.3 on 2022-03-13 20:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurantmenuitem_remove_restaurant_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='postal_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='website',
            field=models.URLField(),
        ),
    ]
