# Generated by Django 4.0.3 on 2022-03-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='section_image1',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='section_image2',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
